apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: my-container
          image: my-registry/my-image:2.0.0
          env:
            - name: MY_ENVIRONMENT
              value: production
