name: Main Workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.echo1.outputs.test}}
    steps:
      - name: Run echo
        id: echo1
        run: |
          echo 'Hello World'
          echo 'Test is working 🚀'
          echo "test=This output is working 😎" >> "$GITHUB_OUTPUT"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Echo Output
        run: echo "${{ needs.first-job.outputs.output1 }}"
  build:
    runs-on: ubuntu-latest
    outputs:
      nodev: ${{ steps.nodev.outputs.NODE_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Store Node Version
        id: nodev
        run: echo "NODE_VERSION=$(node -v)" >> $GITHUB_OUTPUT
      - name: Print Node Version
        run: echo "The used node version is ${{ steps.nodev.outputs.NODE_VERSION }}"
      - run: npm ci
        name: Install deps
      - run: npm run build
        name: Build application
      - run: npm run test:prod
        name: Execute unit tests
      - uses: actions/upload-artifact@v3
        name: Create artifact
        with:
          name: cicd-application
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Deploy
        if: contains(needs.build.outputs.nodev, '.3')
        run: echo "Deployment can be started ✅"
      - uses: actions/download-artifact@v3
        name: Download artifact
        with:
          name: cicd-application
      - run: |
          ls -a
          cd cicd-playground
          ls -a
        name: Display folders
      - name: Run script
        run: ./.github/scripts/first.sh
        shell: bash
  confirmation:
    needs: deploy
    uses: ./.github/workflows/confirmation-reusable.yml
