name: Main Workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.echo1.outputs.test}}
    steps:
      - name: Run echo
        id: echo1
        run: |
          echo 'Hello World'
          echo 'Test is working 🚀'
          echo "test=This output is working 😎" >> "$GITHUB_OUTPUT"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Echo Output
        run: echo "${{ needs.first-job.outputs.output1 }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        name: Install deps
      - run: npm run build
        name: Build application
      - run: npm run test
        name: Execute unit tests
      - uses: actions/upload-artifact@v3
        name: Create artifact
        with:
          name: cicd-application
          path: dist
