name: Main Workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: |
          echo 'Hello World'
          echo 'Test is working 🚀'
